### ISSUE TITLE
nami extension not loading.

### ISSUE THREAD

**Issue by andycandy-dev** [input-output-hk/nami#797]
I'm facing a neverending spinner on nami.
Haven't used the extension for a year or so now.

```
mainPopup.bundle.js:73 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at mainPopup.bundle.js:73:87677
    at u (mainPopup.bundle.js:65:41095)
    at Generator._invoke (mainPopup.bundle.js:65:40883)
    at Generator.next (mainPopup.bundle.js:65:41520)
    at n (mainPopup.bundle.js:73:26169)
    at s (mainPopup.bundle.js:73:26372)
```

that's the `minFeeA` from here

```js
             case 5:
                                return r = e.sent,
                                e.abrupt("return", {
                                    linearFee: {
                                        minFeeA: r.min_fee_a.toString(),
                                        minFeeB: r.min_fee_b.toString()
                                    },
```

**Comment by shroomist** [comment]
@fel-eth12 thanks, no funds lost in this, production keys are backed up, just the testnet tokens locked out. 
it is a bug report - I'm not able to use nami anymore.
